// <auto-generated />
namespace StatsMon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class simplified_model_a_little_more : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(simplified_model_a_little_more));
        
        string IMigrationMetadata.Id
        {
            get { return "201509250032386_simplified_model_a_little_more"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
