// <auto-generated />
namespace StatsMon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactored_report_to_be_event_driven : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactored_report_to_be_event_driven));
        
        string IMigrationMetadata.Id
        {
            get { return "201511230153499_refactored_report_to_be_event_driven"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
