// <auto-generated />
namespace StatsMon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_old_sku_from_DBModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_old_sku_from_DBModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201509260414021_removed_old_sku_from_DBModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
