// <auto-generated />
namespace StatsMon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_uneeded_upperbound : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_uneeded_upperbound));
        
        string IMigrationMetadata.Id
        {
            get { return "201511210132535_removed_uneeded_upperbound"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
