// <auto-generated />
namespace StatsMon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updated_model_based_on_adventureworks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_model_based_on_adventureworks));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241446227_updated_model_based_on_adventureworks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
